---
- hosts: remoteaws
  become: true
  tasks:
  - name: install dependency
    apt:
      name: "{{item}}"
      state: present
      update_cache: yes
    loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - python3-pip

  - name: add GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add docker repository to apt
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: install docker
    apt:
      name: "{{item}}"
      state: latest
      update_cache: yes
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io

  - name: Install Docker Module for Python
    pip:
      name: "{{item}}"
    loop:
      - docker
      - docker-compose

  - name: start docker
    service:
      name: docker
      state: started
      enabled: yes

  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: /home/azureuser/lesson7/docker-compose.yml
      dest: /home/ubuntu/docker-compose.yml
      owner: ubuntu
      group: ubuntu
      mode: '0644'

  - name: Start compose
    docker_compose:
      project_src: /home/ubuntu
      files:
        - docker-compose.yml
      state: present
